FROM node:22-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mkdir -p public

ARG NEXT_PUBLIC_SITE_URL=https://riads.shop
ARG NEXT_PUBLIC_API_URL=https://api.riads.shop
ARG NEXT_PUBLIC_META_PIXEL_ID=
ARG NEXT_PUBLIC_TIKTOK_PIXEL_ID=
ARG NEXT_PUBLIC_SNAP_PIXEL_ID=
ARG NEXT_PUBLIC_ENABLE_META_PIXEL=true
ARG NEXT_PUBLIC_ENABLE_TIKTOK_PIXEL=true
ARG NEXT_PUBLIC_ENABLE_SNAP_PIXEL=true
ARG NEXT_PUBLIC_ENABLE_DEBUG_EVENTS=false

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_META_PIXEL_ID=$NEXT_PUBLIC_META_PIXEL_ID
ENV NEXT_PUBLIC_TIKTOK_PIXEL_ID=$NEXT_PUBLIC_TIKTOK_PIXEL_ID
ENV NEXT_PUBLIC_SNAP_PIXEL_ID=$NEXT_PUBLIC_SNAP_PIXEL_ID
ENV NEXT_PUBLIC_ENABLE_META_PIXEL=$NEXT_PUBLIC_ENABLE_META_PIXEL
ENV NEXT_PUBLIC_ENABLE_TIKTOK_PIXEL=$NEXT_PUBLIC_ENABLE_TIKTOK_PIXEL
ENV NEXT_PUBLIC_ENABLE_SNAP_PIXEL=$NEXT_PUBLIC_ENABLE_SNAP_PIXEL
ENV NEXT_PUBLIC_ENABLE_DEBUG_EVENTS=$NEXT_PUBLIC_ENABLE_DEBUG_EVENTS
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM base AS runner
WORKDIR /app

RUN apk add --no-cache nginx

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
COPY nginx.conf /etc/nginx/nginx.conf
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Easypanel Domains use :80; Next.js runs on :3000 behind nginx
EXPOSE 80 3000

ENTRYPOINT ["/docker-entrypoint.sh"]
