FROM node:22-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mkdir -p public

ARG NEXT_PUBLIC_SITE_URL=https://riads.shop
ARG NEXT_PUBLIC_API_URL=https://api.riads.shop
ARG NEXT_PUBLIC_META_PIXEL_ID=
ARG NEXT_PUBLIC_TIKTOK_PIXEL_ID=
ARG NEXT_PUBLIC_SNAP_PIXEL_ID=
ARG NEXT_PUBLIC_GA4_MEASUREMENT_ID=
ARG NEXT_PUBLIC_GOOGLE_ADS_ID=
ARG NEXT_PUBLIC_GOOGLE_ADS_PURCHASE_SEND_TO=
ARG NEXT_PUBLIC_ENABLE_GOOGLE_ADS=true
ARG NEXT_PUBLIC_ENABLE_META_PIXEL=true
ARG NEXT_PUBLIC_ENABLE_TIKTOK_PIXEL=true
ARG NEXT_PUBLIC_ENABLE_SNAP_PIXEL=true
ARG NEXT_PUBLIC_ENABLE_DEBUG_EVENTS=false

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_META_PIXEL_ID=$NEXT_PUBLIC_META_PIXEL_ID
ENV NEXT_PUBLIC_TIKTOK_PIXEL_ID=$NEXT_PUBLIC_TIKTOK_PIXEL_ID
ENV NEXT_PUBLIC_SNAP_PIXEL_ID=$NEXT_PUBLIC_SNAP_PIXEL_ID
ENV NEXT_PUBLIC_GA4_MEASUREMENT_ID=$NEXT_PUBLIC_GA4_MEASUREMENT_ID
ENV NEXT_PUBLIC_GOOGLE_ADS_ID=$NEXT_PUBLIC_GOOGLE_ADS_ID
ENV NEXT_PUBLIC_GOOGLE_ADS_PURCHASE_SEND_TO=$NEXT_PUBLIC_GOOGLE_ADS_PURCHASE_SEND_TO
ENV NEXT_PUBLIC_ENABLE_GOOGLE_ADS=$NEXT_PUBLIC_ENABLE_GOOGLE_ADS
ENV NEXT_PUBLIC_ENABLE_META_PIXEL=$NEXT_PUBLIC_ENABLE_META_PIXEL
ENV NEXT_PUBLIC_ENABLE_TIKTOK_PIXEL=$NEXT_PUBLIC_ENABLE_TIKTOK_PIXEL
ENV NEXT_PUBLIC_ENABLE_SNAP_PIXEL=$NEXT_PUBLIC_ENABLE_SNAP_PIXEL
ENV NEXT_PUBLIC_ENABLE_DEBUG_EVENTS=$NEXT_PUBLIC_ENABLE_DEBUG_EVENTS
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM base AS runner
WORKDIR /app

RUN apk add --no-cache wget

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=80

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=10s --start-period=90s --retries=5 \
  CMD wget -q -O /dev/null http://127.0.0.1:80/ || exit 1

CMD ["node", "server.js"]
